#!/bin/dash

# ==============================================================================
# tigger-log
# Written by: Jinming Liu <z5373811@unsw.edu.au>
# Date: 2022-07-11
# For COMP2041/9044 Assignment 1
# ==============================================================================

sort -r < .tigger/commit.log

exit 0